name: NuGet.Insights
services:
  - name: website
    project: src/Website/Website.csproj
    bindings:
      - protocol: "http"
  - name: worker
    azureFunction: src/Worker/
  - name: storage
    # Patched version of Azurite while blocking issues exist.
    # Tracking issue: https://github.com/NuGet/Insights/issues/30
    image: ghcr.io/joelverhagen/azurite:edge
    volumes:
      - target: /data
        source: ./azurite/
    bindings:
      - name: blobs
        port: 10000
      - name: queues
        port: 10001
      - name: tables
        port: 10002
