schedules:
  - cron: "0 0 * * *"
    displayName: Run daily
    branches:
      include:
      - main
    always: true
trigger: none

name: Check for latest Azure Functions Host - $(Date:yyyyMMdd).$(Rev:r)
appendCommitMessageToRunName: false

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
    stages:
    - stage: Stage
      jobs:
      - job: HostJob
        steps:
        - task: PowerShell@2
          displayName: Configure git
          inputs:
            targetType: inline
            script: |
              git config --global user.email "nugetservereng@microsoft.com"
              git config --global user.name "NuGet Insights automation"
        - task: PowerShell@2
          displayName: Execute script
          inputs:
            targetType: "filePath"
            filePath: $(Build.SourcesDirectory)/scripts/Invoke-AzureFunctionsHostUpdate.ps1
            arguments: >
              -GitAuthorizationHeader "Bearer $(System.AccessToken)"
              -PullRequestAuthorizationHeader "Bearer $(System.AccessToken)"
