name: Build

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, labeled ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
    - uses: Azure/get-keyvault-secrets@v1
      # if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'run tests')
      with:
        keyvault: explorepackages
        secrets: 'explorepackages-BlobQueueTableFullAccessSas, explorepackages-BlobReadSas'
      id: keyVault

  markdown-link-check:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
