name: Build

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, labeled ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - run: dotnet restore
    - run: dotnet build --no-restore
    - uses: Azure/login@v1
      if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'run tests')
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        allow-no-subscriptions: true
    - uses: Azure/get-keyvault-secrets@v1
      if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'run tests')
      with:
        keyvault: ${{ secrets.NUGETINSIGHTS_KEYVAULTNAME }}
        secrets: '${{ secrets.NUGETINSIGHTS_STORAGESASSECRETNAME }}, ${{ secrets.NUGETINSIGHTS_STORAGEBLOBREADSASSECRETNAME }}'
      id: keyVault
    - run: dotnet test --no-build --verbosity normal
      if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'run tests')
      env:
        NUGETINSIGHTS_STORAGEACCOUNTNAME: ${{ secrets.NUGETINSIGHTS_STORAGEACCOUNTNAME }}
        NUGETINSIGHTS_STORAGESAS: ${{ steps.keyVault.outputs[secrets.NUGETINSIGHTS_STORAGESASSECRETNAME] }}
        NUGETINSIGHTS_STORAGEBLOBREADSAS: ${{ steps.keyVault.outputs[secrets.NUGETINSIGHTS_STORAGEBLOBREADSASSECRETNAME] }}   

  markdown-link-check:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
