name: Build

on:
  schedule:
    - cron: '0 2 * * *'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - run: dotnet restore
    - run: dotnet build --no-restore
    - run: dotnet test --no-build --verbosity normal
      env:
        EXPLOREPACKAGES_STORAGECONNECTIONSTRING: ${{ secrets.EXPLOREPACKAGES_STORAGECONNECTIONSTRING }}

  markdown-link-check:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
